version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: flightspy_backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:7.0-alpine
    container_name: flightspy_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: