# Generated by Django 5.1.5 on 2025-02-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(max_length=6)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('icao_type', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_s', models.CharField(blank=True, max_length=10, null=True)),
                ('registration', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner_country_iso_name', models.CharField(blank=True, max_length=10, null=True)),
                ('registered_owner_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_owner_operator_flag_code', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('url_photo', models.URLField(blank=True, null=True)),
                ('url_photo_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icao', models.CharField(blank=True, max_length=10, null=True)),
                ('iata', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_iso_name', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=5, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squawk_code', models.IntegerField(blank=True, null=True)),
                ('flight_callsign', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('valid_position', models.BooleanField(default=False)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('vertical_rate', models.IntegerField(blank=True, null=True)),
                ('track', models.IntegerField(blank=True, null=True)),
                ('valid_track', models.BooleanField(default=False)),
                ('speed_in_knots', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('seen', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='dump1090_collector.aircraft')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='dump1090_collector.airline')),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_flights', to='dump1090_collector.airport')),
                ('origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_flights', to='dump1090_collector.airport')),
            ],
        ),
    ]
