# Generated by Django 5.1.5 on 2025-01-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(blank=True, max_length=6)),
                ('squawk_code', models.IntegerField(blank=True)),
                ('flight_callsign', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('valid_position', models.BinaryField()),
                ('altitude', models.IntegerField(blank=True)),
                ('vertical_rate', models.IntegerField(blank=True)),
                ('track', models.IntegerField(blank=True)),
                ('valid_track', models.BinaryField()),
                ('speed_in_knots', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('seen', models.IntegerField(default=0)),
            ],
        ),
    ]
