# Generated by Django 5.1.5 on 2025-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(blank=True, max_length=6, null=True)),
                ('squawk_code', models.IntegerField(blank=True, null=True)),
                ('flight_callsign', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('valid_position', models.BooleanField(default=False)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('vertical_rate', models.IntegerField(blank=True, null=True)),
                ('track', models.IntegerField(blank=True, null=True)),
                ('valid_track', models.BooleanField(default=False)),
                ('speed_in_knots', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('seen', models.IntegerField(default=0)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('icao_type', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_s', models.CharField(blank=True, max_length=10, null=True)),
                ('registration', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner_country_iso_name', models.CharField(blank=True, max_length=10, null=True)),
                ('registered_owner_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_owner_operator_flag_code', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('url_photo', models.URLField(blank=True, null=True)),
                ('url_photo_thumbnail', models.URLField(blank=True, null=True)),
                ('callsign', models.CharField(blank=True, max_length=20, null=True)),
                ('callsign_icao', models.CharField(blank=True, max_length=20, null=True)),
                ('callsign_iata', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('midpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
