# Generated by Django 5.1.5 on 2025-01-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump1090_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdata',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='callsign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='callsign_iata',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='callsign_icao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='icao_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='midpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='mode_s',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='registered_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='registered_owner_country_iso_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='registered_owner_country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='registered_owner_operator_flag_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='url_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='url_photo_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='flight_callsign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='hex_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='squawk_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='valid_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='valid_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='vertical_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
