# Generated by Django 5.1.5 on 2025-01-29 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump1090_collector', '0002_remove_flightdata_airline_remove_flightdata_midpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(max_length=6, unique=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('icao_type', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_s', models.CharField(blank=True, max_length=10, null=True)),
                ('registration', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner_country_iso_name', models.CharField(blank=True, max_length=10, null=True)),
                ('registered_owner_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_owner_operator_flag_code', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('url_photo', models.URLField(blank=True, null=True)),
                ('url_photo_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icao', models.CharField(blank=True, max_length=10, null=True)),
                ('iata', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_iso_name', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=5, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_callsign',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_country',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_country_iso',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_iata',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_icao',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='airline_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='callsign_iata',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='callsign_icao',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_country_iso_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_country_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_elevation',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_iata_code',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_icao_code',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_latitude',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_longitude',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination_municipality',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='hex_id',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='icao_type',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='mode_s',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_country_iso_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_country_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_elevation',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_iata_code',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_icao_code',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_latitude',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_longitude',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_municipality',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='registered_owner',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='registered_owner_country_iso_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='registered_owner_country_name',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='registered_owner_operator_flag_code',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='url_photo',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='url_photo_thumbnail',
        ),
        migrations.AddField(
            model_name='flightdata',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='dump1090_collector.aircraft'),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='dump1090_collector.airline'),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='destination_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_flights', to='dump1090_collector.airport'),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_flights', to='dump1090_collector.airport'),
        ),
    ]
