# Generated by Django 5.1.5 on 2025-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump1090_collector', '0003_aircraft_airline_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='hex_id',
            field=models.CharField(max_length=6),
        ),
    ]
